name: "Build iRODS clients"

description: "An environment for building iRODS clients"

inputs:
  build-image:
    description: "Docker image to use for the build environment"
    required: true
    default: "ghcr.io/wtsi-npg/ub-18.04-irods-clients-dev-4.2.11:latest"
  build-script:
    description: "Build script to run in the container"
    required: true
    default: ".github/workflows/build.sh"
  docker-network:
    description: "Docker network to use for the container"
    required: false
    default: "host"

# The simple approach to implementing this Action described here:
# https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action
# does not work because a value given in input.build-image is not available to the
# run.image field.
#
# One workaround is described here:
# https://github.com/JavierZolotarchuk/parameterizable-docker-action-example
#
# Credit to JavierZolotarchuk for the workaround described in the link above. I've used
# it here. In order for the Action to be able to use Docker services set up by the calling
# workflow, it must know the name of the Docker network to use. This is passed in as a
# another parameter.

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.build-image }}
    - ${{ inputs.build-script }}
    - ${{ inputs.docker-network }}
